//
// init.rs
// motive
// 
// Author: Wess Cope (me@wess.io)
// Created: 12/01/2021
// 
// Copywrite (c) 2021 Wess.io
//

use std::{
  env,
  path::Path,
  fs::File,
  io::{
    self,
    Write,
    prelude::*,
  },
  collections::HashMap,
};

use clap::{App};

use oxide::{
  console_error,
  console_panic,
  console_success,
};


const DEFAULT_ALIBI:&str = r#"# Generated by Motive

hello: 
  echo "Hello world"

"#;

pub struct Init {}

impl Init {
  pub fn app() -> App<'static> {
    App::new("init")
    .about("Creates a new 'alibi' file in current directory")  
  }

  pub fn run() {
    let cwd = env::current_dir().unwrap();
    let file_path = format!("{}/alibi", cwd.to_str().unwrap());
    let path = Path::new(file_path.as_str());

    let mut file = match File::create(&path) {
      Ok(file) => file,
      Err(e) => {
        console_panic!("Unable to create alibi config file: {}", e);
      }
    };

    match file.write_all(DEFAULT_ALIBI.as_bytes()) {
      Ok(_) => {
        console_success!("Created alibi config file: {}", file_path);
      }
      Err(e) => {
        console_error!("Unable to write to alibi config file: {}", e);
      }
    }
  }
}
